import type { Journey } from './types'

export const journeys: Journey[] = [
  {
    id: 'sleep-mastery',
    name: 'Sleep Mastery',
    description: 'A 7-day program to train your brain for deeper, more restorative sleep. Each day gradually introduces lower frequencies.',
    category: 'sleep',
    icon: '🌙',
    color: '#6366f1',
    days: [
      {
        day: 1,
        presetId: 'deep-relax',
        title: 'Relaxation Foundation',
        tip: 'Start 30 minutes before your target bedtime. Dim all lights and put your phone on Do Not Disturb.',
      },
      {
        day: 2,
        presetId: 'deep-relax',
        title: 'Deepening Relaxation',
        tip: 'Try lying down with your eyes closed today. Focus on the sensation of each exhale.',
      },
      {
        day: 3,
        presetId: 'power-nap',
        title: 'Theta Gateway',
        tip: 'Today we introduce theta waves. Let your thoughts drift without engaging with them.',
      },
      {
        day: 4,
        presetId: 'sleep-drift',
        title: 'First Delta Session',
        tip: 'Your brain is now ready for delta frequencies. Let the tones carry you to sleep — no need to stay awake.',
      },
      {
        day: 5,
        presetId: 'sleep-drift',
        title: 'Deepening Sleep',
        tip: 'Keep a consistent bedtime. Your brain is starting to associate these tones with sleep onset.',
      },
      {
        day: 6,
        presetId: 'sleep-drift',
        title: 'Full Descent',
        tip: 'Enable the breathing guide tonight. Slow breathing combined with delta waves creates powerful sleep induction.',
      },
      {
        day: 7,
        presetId: 'sleep-drift',
        title: 'Sleep Integration',
        tip: 'Final session. After tonight, your brain will have stronger neural pathways for entering deep sleep.',
      },
    ],
  },
  {
    id: 'meditation-fundamentals',
    name: 'Meditation Foundations',
    description: 'Build a consistent meditation practice over 7 days. Progressively deepens from alpha relaxation to sustained theta meditation.',
    category: 'meditation',
    icon: '🧘',
    color: '#a855f7',
    days: [
      {
        day: 1,
        presetId: 'quick-calm',
        title: 'Finding Stillness',
        tip: 'Sit comfortably with your back straight. Simply listen to the tones — no need to "try" to meditate.',
      },
      {
        day: 2,
        presetId: 'quick-calm',
        title: 'Breath Awareness',
        tip: 'Enable the breathing guide today. Let it set your rhythm while the alpha waves calm your mind.',
      },
      {
        day: 3,
        presetId: 'deep-relax',
        title: 'Extending Practice',
        tip: 'Today is a longer session. When your mind wanders, gently return attention to the tones.',
      },
      {
        day: 4,
        presetId: 'creative-theta',
        title: 'Entering Theta',
        tip: 'Theta is where deep meditation happens. You may experience vivid imagery — let it flow.',
      },
      {
        day: 5,
        presetId: 'creative-theta',
        title: 'Deepening Practice',
        tip: 'Try not moving at all today. Physical stillness helps the mind settle into deeper states.',
      },
      {
        day: 6,
        presetId: 'theta-meditation',
        title: 'Full Theta Session',
        tip: 'Today is a full 35-minute theta session. This is the deepest meditation preset. Trust the process.',
      },
      {
        day: 7,
        presetId: 'theta-meditation',
        title: 'Integration',
        tip: 'Final session. Sit for a minute after the session ends to carry the calm into your day.',
      },
    ],
  },
  {
    id: 'focus-intensive',
    name: 'Focus Intensive',
    description: '7 days to sharpen your concentration. Builds from calm focus to peak cognitive performance with gamma entrainment.',
    category: 'focus',
    icon: '🎯',
    color: '#ef4444',
    days: [
      {
        day: 1,
        presetId: 'quick-calm',
        title: 'Calm Baseline',
        tip: 'Start with alpha to establish a calm, clear baseline. Use this time to set your intention for the week.',
      },
      {
        day: 2,
        presetId: 'focus-session',
        title: 'SMR Training',
        tip: 'Sensorimotor rhythm (15 Hz) is associated with calm alertness. Work on a single task during this session.',
      },
      {
        day: 3,
        presetId: 'focus-session',
        title: 'Deep Work Block',
        tip: 'Pair today\'s session with your most cognitively demanding task. Minimize distractions.',
      },
      {
        day: 4,
        presetId: 'focus-session',
        title: 'Sustained Attention',
        tip: 'If your attention drifts, acknowledge it and return to the task. The SMR rhythm supports this recovery.',
      },
      {
        day: 5,
        presetId: 'gamma-boost',
        title: 'First Gamma Session',
        tip: '40 Hz gamma is linked to peak cognitive performance. You may feel increased mental clarity.',
      },
      {
        day: 6,
        presetId: 'gamma-boost',
        title: 'Cognitive Peak',
        tip: 'Use this session for creative problem-solving or learning new material. Gamma enhances memory encoding.',
      },
      {
        day: 7,
        presetId: 'gamma-boost',
        title: 'Integration',
        tip: 'Final session. You\'ve trained your brain through alpha → SMR → gamma. Use any preset as needed going forward.',
      },
    ],
  },
  {
    id: 'gateway-discovery',
    name: 'Gateway Discovery',
    description: 'Progressive introduction to Monroe-style focus levels. Over 7 days, experience Focus 10, Harmonic Box, Focus 12, and Focus 15 — states most people never access.',
    category: 'advanced',
    icon: '🔮',
    color: '#d946ef',
    days: [
      {
        day: 1,
        presetId: 'gateway-focus10',
        title: 'Mind Awake, Body Asleep',
        tip: 'Lie down in a dark room with headphones. Focus on the phrase "mind awake, body asleep" as the tones deepen.',
      },
      {
        day: 2,
        presetId: 'gateway-focus10',
        title: 'Deepening Focus 10',
        tip: 'Today, try to notice the moment your body "disappears." You may feel floating — this is normal.',
      },
      {
        day: 3,
        presetId: 'harmonic-box',
        title: 'Harmonic Resonance',
        tip: 'The dual-carrier pattern creates a fuller sound field. Let the harmonics wash over you.',
      },
      {
        day: 4,
        presetId: 'gateway-focus12',
        title: 'Entering Focus 12',
        tip: 'Focus 12 is expanded awareness. You may experience vivid imagery or sensations of expansion.',
      },
      {
        day: 5,
        presetId: 'gateway-focus12',
        title: 'Exploring Focus 12',
        tip: 'Set an intention before the session. In Focus 12, insights often arise spontaneously.',
      },
      {
        day: 6,
        presetId: 'gateway-focus15',
        title: 'The No-Time State',
        tip: 'Focus 15 is very deep. Don\'t try to control the experience — simply observe.',
      },
      {
        day: 7,
        presetId: 'gateway-focus15',
        title: 'Integration',
        tip: 'Final session. After reaching Focus 15, you\'ve accessed states most people never experience.',
      },
    ],
  },
  {
    id: 'consciousness-explorer',
    name: 'Consciousness Explorer',
    description: 'For experienced users. Progresses through all focus levels to Focus 21 — the deepest Gateway state at the edge of conscious perception.',
    category: 'advanced',
    icon: '✨',
    color: '#4f46e5',
    days: [
      {
        day: 1,
        presetId: 'gateway-focus12',
        title: 'Quick Review',
        tip: 'If you\'re familiar with Focus 10/12, this session serves as a warm-up review.',
      },
      {
        day: 2,
        presetId: 'gateway-focus15',
        title: 'Approaching No-Time',
        tip: 'Let go of any sense of time passing. The 2 Hz delta-theta border is profoundly still.',
      },
      {
        day: 3,
        presetId: 'gateway-focus15',
        title: 'Deepening No-Time',
        tip: 'Stay in a comfortable position you can hold for the full session without moving.',
      },
      {
        day: 4,
        presetId: 'gateway-focus21',
        title: 'First Contact',
        tip: 'Focus 21 is described as the "edge of perception." Remain a detached observer.',
      },
      {
        day: 5,
        presetId: 'gateway-focus21',
        title: 'Expanding the Edge',
        tip: 'Each session at Focus 21 opens the state further. Keep a journal of experiences.',
      },
      {
        day: 6,
        presetId: 'gateway-focus21',
        title: 'Deep Exploration',
        tip: 'You are accessing the deepest state in the app. Trust the return phase to bring you back.',
      },
      {
        day: 7,
        presetId: 'gateway-focus21',
        title: 'Integration',
        tip: 'Final session. Sit quietly for 5 minutes after — don\'t jump immediately into activity.',
      },
    ],
  },
  {
    id: 'stress-relief-program',
    name: 'Stress Relief Program',
    description: 'Evidence-based progressive relaxation and anxiety reduction over 7 days. Builds from quick alpha calm to targeted anxiety relief and earth grounding.',
    category: 'relaxation',
    icon: '🫧',
    color: '#06b6d4',
    days: [
      {
        day: 1,
        presetId: 'quick-calm',
        title: 'Establishing Calm',
        tip: 'Find a quiet space. Simply breathe and let the alpha waves slow your racing thoughts.',
      },
      {
        day: 2,
        presetId: 'quick-calm',
        title: 'Breath + Beats',
        tip: 'Enable the breathing guide today. Slow breathing amplifies the calming effect.',
      },
      {
        day: 3,
        presetId: 'deep-relax',
        title: 'Longer Relaxation',
        tip: 'Extended session today. Notice how your body feels different at minute 10 vs minute 1.',
      },
      {
        day: 4,
        presetId: 'anxiety-relief',
        title: 'Targeted Relief',
        tip: 'This session includes a brief theta dip for emotional processing. Feelings may surface — let them.',
      },
      {
        day: 5,
        presetId: 'anxiety-relief',
        title: 'Deepening Relief',
        tip: 'Use this session when anxiety peaks. The alpha-theta pattern is clinically validated.',
      },
      {
        day: 6,
        presetId: 'schumann-resonance',
        title: 'Earth Grounding',
        tip: 'The 7.83 Hz frequency matches the Earth\'s natural rhythm. Feel rooted and connected.',
      },
      {
        day: 7,
        presetId: 'schumann-resonance',
        title: 'Integration',
        tip: 'Final session. You now have multiple tools for managing stress — use them regularly.',
      },
    ],
  },
  {
    id: 'lucid-dream-training',
    name: 'Lucid Dream Training',
    description: 'Progressive 7-day training for lucid dream induction. Builds body awareness, theta familiarity, and the oscillation technique for maintaining awareness at the sleep boundary.',
    category: 'sleep',
    icon: '🦋',
    color: '#8b5cf6',
    days: [
      {
        day: 1,
        presetId: 'deep-relax',
        title: 'Body Scan',
        tip: 'Practice full body relaxation with alpha waves. Lucid dreaming starts with body awareness.',
      },
      {
        day: 2,
        presetId: 'power-nap',
        title: 'Theta Familiarity',
        tip: 'Get comfortable with the theta state. Notice the hypnagogic imagery as you drift off.',
      },
      {
        day: 3,
        presetId: 'power-nap',
        title: 'Holding the Edge',
        tip: 'Today, try to stay aware as you feel drowsy. Don\'t fight sleep — just observe.',
      },
      {
        day: 4,
        presetId: 'sleep-drift',
        title: 'Surrender to Delta',
        tip: 'Let yourself fall fully asleep. This trains your brain to associate the tones with dreaming.',
      },
      {
        day: 5,
        presetId: 'lucid-gateway',
        title: 'The Oscillation Method',
        tip: 'The theta-delta oscillation keeps a thread of awareness at the sleep boundary. Set a dream intention.',
      },
      {
        day: 6,
        presetId: 'lucid-gateway',
        title: 'Dream Entry',
        tip: 'Same protocol. This time, as imagery appears, try to "step into" the scene without forcing it.',
      },
      {
        day: 7,
        presetId: 'lucid-gateway',
        title: 'Full Practice',
        tip: 'Final night. Combine the tones with a WILD intention: "I will recognize I\'m dreaming."',
      },
    ],
  },
  // ── Guided Gateway Experience ──────────────────────────────
  {
    id: 'guided-gateway-experience',
    name: 'Guided Gateway Experience',
    description: 'Progressive 6-day guided meditation program based on the Gateway process. Voice-narrated sessions take you from Focus 10 through Focus 21 with full preparation protocols.',
    category: 'guided',
    icon: '🌀',
    color: '#7c3aed',
    days: [
      {
        day: 1,
        presetId: 'guided-foundation',
        title: 'Foundation',
        tip: 'Full guided introduction. Learn the Energy Conversion Box, Resonant Tuning, REBAL, and Affirmation. Progressive relaxation to Focus 10.',
      },
      {
        day: 2,
        presetId: 'guided-deepening',
        title: 'Deepening',
        tip: 'Abbreviated prep with rapid Focus 10 entry. 18 minutes of uninterrupted freeflow time to deepen your practice.',
      },
      {
        day: 3,
        presetId: 'guided-expansion',
        title: 'Expansion',
        tip: 'Journey from Focus 10 into Focus 12 — expanded awareness. Experience the shift from body-asleep to wider perception.',
      },
      {
        day: 4,
        presetId: 'guided-liberation',
        title: 'Liberation',
        tip: 'Progress through Focus 12 to Focus 15 — the "No-Time" state. Release from the constraints of time and space.',
      },
      {
        day: 5,
        presetId: 'guided-bridging',
        title: 'Bridging',
        tip: 'Rapid transit through all focus levels to Focus 21 — "The Bridge." The deepest guided state at the edge of perception.',
      },
      {
        day: 6,
        presetId: 'guided-integration',
        title: 'Integration',
        tip: 'Self-directed full-spectrum freeflow. Minimal guidance — you choose your own depth and pace through all focus levels.',
      },
    ],
  },
]
